#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
dunst &

# Keyboard repeat delay and rate
xset r rate 250 30

# Keyboard layout
setxkbmap -layout 'us,ru' -option 'grp:caps_toggle'

WALLPAPER_FILE=~/.config/bspwm/wallpaper.png

feh --bg-scale "$WALLPAPER_FILE"

wal -i "$WALLPAPER_FILE"
. "${HOME}/.cache/wal/colors.sh"

sh ~/.config/polybar/launch.sh

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Setup monitor
xrandr --output HDMI-0 --primary --output DVI-D-0 --right-of HDMI-0
bspc wm -O HDMI-0 DVI-D-0
bspc monitor HDMI-0 -d 1 2 3 4 
bspc monitor DVI-D-0 -d	5 6 7 8 

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false

bspc subscribe pointer_action
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
